### ISSUE TITLE
Removing permissions from roles causes ISE

### ISSUE THREAD

**Issue by toirl** [ringo-framework/ringo#19]
If the admin role tries to remove permissions from a specific role this cases a traceback:

`2016-05-04 15:04:46,687 INFO  [ringo.views.request][waitress] User admin edited Role 1
2016-05-04 15:04:46,703 ERROR [waitress][waitress] Exception when serving /roles/update/1
Traceback (most recent call last):
  File "/home/torsten/bewec/env/lib/python2.7/site-packages/waitress-0.9.0-py2.7.egg/waitress/channel.py", line 338, in service
    task.service()
  File "/home/torsten/bewec/env/lib/python2.7/site-packages/waitress-0.9.0-py2.7.egg/waitress/task.py", line 169, in service
    self.execute()
  File "/home/torsten/bewec/env/lib/python2.7/site-packages/waitress-0.9.0-py2.7.egg/waitress/task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/home/torsten/bewec/env/lib/python2.7/site-packages/pyramid-1.7b1-py2.7.egg/pyramid/router.py", line 236, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/torsten/bewec/env/lib/python2.7/site-packages/pyramid-1.7b1-py2.7.egg/pyramid/router.py", line 211, in invoke_subrequest
    response = handle_request(request)
  File "/home/torsten/bewec/lib/ringo/ringo/tweens/csp.py", line 54, in csp_tween
    return handler(request)
  File "/home/torsten/bewec/lib/ringo/ringo/tweens/clickjacking.py", line 8, in clickjacking_tween
    return handler(request)
  File "/home/torsten/bewec/lib/ringo/ringo/tweens/secure_headers.py", line 12, in secure_headers_tween
    return handler(request)
  File "/home/torsten/bewec/env/lib/python2.7/site-packages/pyramid-1.7b1-py2.7.egg/pyramid/tweens.py", line 20, in excview_tween
    response = handler(request)
  File "/home/torsten/bewec/env/lib/python2.7/site-packages/pyramid_tm-0.12.1-py2.7.egg/pyramid_tm/__init__.py", line 101, in tm_tween
    reraise(*exc_info)
  File "/home/torsten/bewec/env/lib/python2.7/site-packages/pyramid_tm-0.12.1-py2.7.egg/pyramid_tm/__init__.py", line 83, in tm_tween
    response = handler(request)
  File "/home/torsten/bewec/env/lib/python2.7/site-packages/pyramid-1.7b1-py2.7.egg/pyramid/router.py", line 158, in handle_request
    view_name
  File "/home/torsten/bewec/env/lib/python2.7/site-packages/pyramid-1.7b1-py2.7.egg/pyramid/view.py", line 546, in _call_view
    response = view_callable(context, request)
  File "/home/torsten/bewec/env/lib/python2.7/site-packages/pyramid-1.7b1-py2.7.egg/pyramid/viewderivers.py", line 293, in _secured_view
    return view(context, request)
  File "/home/torsten/bewec/env/lib/python2.7/site-packages/pyramid-1.7b1-py2.7.egg/pyramid/viewderivers.py", line 256, in wrapper
    response = view(context, request)
  File "/home/torsten/bewec/env/lib/python2.7/site-packages/pyramid-1.7b1-py2.7.egg/pyramid/viewderivers.py", line 425, in rendered_view
    result = view(context, request)
  File "/home/torsten/bewec/env/lib/python2.7/site-packages/pyramid-1.7b1-py2.7.egg/pyramid/viewderivers.py", line 146, in _requestonly_view
    response = view(request)
  File "/home/torsten/bewec/lib/ringo/ringo/views/base/update.py", line 44, in update
    if handle_POST_request(form, request, callback, 'update', renderers):
  File "/home/torsten/bewec/lib/ringo/ringo/views/request.py", line 225, in handle_POST_request
    msg = _(generate_save_errormessage(event), mapping=translation_params)
  File "/home/torsten/bewec/lib/ringo/ringo/lib/i18n.py", line 60, in auto_translate
    translated = Template(ts).safe_substitute(mapping)
  File "/usr/lib64/python2.7/string.py", line 205, in safe_substitute
    return self.pattern.sub(convert, self.template)
  File "/usr/lib64/python2.7/string.py", line 196, in convert
    return '%s' % (mapping[braced],)
  File "/home/torsten/bewec/lib/ringo/ringo/model/base.py", line 156, in __str__
    return self.__unicode__()
  File "/home/torsten/bewec/lib/ringo/ringo/model/base.py", line 188, in __unicode__
    modul = load_modul(self)
  File "/home/torsten/bewec/lib/ringo/ringo/model/base.py", line 118, in load_modul
    modul = session.query(ModulItem).filter_by(id=mid).one()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2693, in one
    ret = list(self)
  File "/home/torsten/bewec/lib/ringo/ringo/lib/sql/query.py", line 66, in __iter__
    return Query.__iter__(self)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2736, in __iter__
    return self._execute_and_instances(context)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2749, in _execute_and_instances
    close_with_result=True)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2740, in _connection_from_session
    **kw)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 893, in connection
    execution_options=execution_options)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 898, in _connection_for_bind
    engine, execution_options)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 313, in _connection_for_bind
    self._assert_active()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/session.py", line 214, in _assert_active
    % self._rollback_exception
InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: DELETE statement on table 'nm_action_roles' expected to delete 1 row(s); Only 0 were matched.`

**Comment by toirl** [comment]
This fix seems to fix the concrete defect in the software but causes other errors.
In concrete: in eFa - another ringo based application - standins can not be set.

So I will reopen this issue. Further the change has been reverted.
